---
- name: 02-ipaddress.yml
  hosts: LNX2
  gather_facts: false
  tasks: 
  - name: set ip 
    ansible.builtin.copy:
      content: |
        auto ens33
        iface ens33 inet static
          address 172.16.20.11/24
          gateway 172.16.20.254

        auto ens35
        iface ens35 inet static
          address 10.1.1.22/24
      dest: /etc/network/interfaces
  - name: set dns 
    ansible.builtin.copy:
      content: nameserver 172.16.20.10
      dest: /etc/resolv.conf

  - name: reboot
    ansible.builtin.reboot:

- name: 02-ipaddress.yml
  hosts: WIN2
  gather_facts: false
  tasks: 
  - name: set ip
    ansible.windows.win_shell: netsh int ip set address Ethernet0 static 172.16.10.11 255.255.255.0 172.16.10.254
  - name: set preffered dns
    ansible.windows.win_shell: netsh int ip set dnsserver ethernet0 static 172.16.10.10 validate=no
  - name: set alt dns
    ansible.windows.win_shell: netsh int ip add dnsserver ethernet0 172.16.10.11 validate=no

- name: 02-ipaddress.yml
  hosts: SW3
  gather_facts: false
  tasks: 
  - name: create vlan 99
    cisco.ios.ios_l3_interfaces:
      config:
        - name: Vlan99
          ipv4:
            - address: 172.16.99.3/29

- name: 02-ipaddress.yml
  hosts: RTR1
  gather_facts: false
  tasks: 
  - name: enable encapsulation dot1q
    cisco.ios.ios_config:
      lines: encapsulation dot1q {{item}}
      parents: interface GigabitEthernet0/1.{{item}}
    with_items:
      - 10
      - 20
      - 99
  - name: set ip 
    cisco.ios.ios_l3_interfaces:
      config:
        - name: GigabitEthernet0/1.10
          ipv4:
            - address: 172.16.10.254/24
        - name: GigabitEthernet0/1.20
          ipv4:
            - address: 192.168.10.254/24
        - name: GigabitEthernet0/1.99
          ipv4:
            - address: 172.16.99.6/29
        - name: GigabitEthernet0/0
          ipv4:
            - address: 24.48.72.1/28
        - name: Loopback100
          ipv4:
            - address: 1.1.1.1/32

- name: 02-ipaddress.yml
  hosts: RTR2
  gather_facts: false
  tasks: 
  - name: set ip 
    cisco.ios.ios_l3_interfaces:
      config:
        - name: GigabitEthernet0/0
          ipv4:
            - address: 24.48.72.14/28
        - name: GigabitEthernet0/1
          ipv4:
            - address: 172.16.20.254/24

- name: 02-ipaddress.yml
  hosts: RTR1 RTR2 
  gather_facts: false
  tasks: 
  - name: no shutdown interface
    cisco.ios.ios_interfaces:
      config:
        - name: GigabitEthernet0/0
          enabled: true
        - name: GigabitEthernet0/1
          enabled: true
        - name: Loopback100
          enabled: true

- name: 02-ipaddress.yml
  hosts: cisco
  gather_facts: false
  tasks: 
  - name: no shutdown interface
    cisco.ios.ios_interfaces:
      config:
        - name: Vlan99
          enabled: true

  - name: save configuration
    cisco.ios.ios_config:
      save_when: modified
        
                

        







    


  
        

    
